#!/usr/bin/env bash

choice=$(dmenu -nb "#001514" -sb "#5B5F97" -h '24px' -fn 'CaskaydiaCove Nerd Font' -p 'Brightness(%): ')
# quit if quit
if [[ "$choice" == "quit" ]]; then
    echo "Program Terminated." && exit 1
# change brightness
elif [ "$choice" ]; then
    brightnessctl set "${choice}%"
else
    echo "Program Terminated." && exit 1
fi
